apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DB_HOST: postgres-service
  DB_NAME: appdb
  DB_USER: appuser
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
data:
  init.sql: |
    create table employees(id serial primary key,name varchar(100));
    insert into employees(name) values ('Akshay'),('John'),('Jane'),('Mike'),('Sara');
